name: Build source code and send to Capgo

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build code and release
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 9
      - name: Install dependencies
        id: install_code
        run: pnpm i
      - name: Lint
        id: lint_code
        run: pnpm lint
      - name: Build
        id: build_code
        run: pnpm build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
